image: quartic/uber-builder

cache:
  key: "$CI_BUILD_NAME"
  paths:
     - .gradle/wrapper
     - .gradle/caches

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

build:
  stage: build
  script:
    - ./gradlew docker --parallel
  except:
    - develop

build_and_push:
  stage: build
  script:
    - ./gradlew dockerPush --parallel
  only:
    - develop
    - tags
